In [1]:
import pandas as pd

In [213]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains

In [221]:
import time

In [5]:
from bs4 import BeautifulSoup as BS

In [263]:
driver = webdriver.Chrome('./chromedriver')

# Wikipedia

In [8]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [11]:
html = driver.page_source

In [12]:
soup = BS(html, 'html.parser')

In [32]:
table = soup.findAll("table",{"class":"wikitable sortable jquery-tablesorter"})[0]

In [33]:
len(table.find("tbody").findAll("tr")) #Total video list

30

In [63]:
video_df = pd.DataFrame({"Rank":[],"Name":[],"Artist":[],"Upload Date":[],"Views (billions)":[]})

In [64]:
for row in table.find("tbody").findAll("tr"):
    video_df = video_df.append(pd.DataFrame({
                                "Rank": row.findAll("td")[0].text.replace(".",""),
                                "Name": row.findAll("td")[1].find("a").text,
                                "Artist": row.findAll("td")[2].text,
                                "Upload Date": row.findAll("td")[4].text,
                                "Views (billions)": row.findAll("td")[3].text
                                },index=[0]))

In [65]:
video_df

,Rank,Name,Artist,Upload Date,Views (billions)
0,1,Baby Shark Dance,Pinkfong Kids' Songs & Stories,"June 17, 2016",8.81
0,2,Despacito,Luis Fonsi,"January 12, 2017",7.40
0,3,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.47
0,4,Shape of You,Ed Sheeran,"January 30, 2017",5.35
0,5,See You Again,Wiz Khalifa,"April 6, 2015",5.14
0,6,Masha and the Bear,Get Movies,"January 31, 2012",4.44
0,7,Uptown Funk,Mark Ronson,"November 19, 2014",4.20
0,8,[32],Cocomelon – Nursery Rhymes,"May 2, 2018",4.16
0,9,[33],Miroshka TV,"February 27, 2018",4.16
0,10,Gangnam Style,Psy,"July 15, 2012",4.09
0,11,[36],ChuChu TV,"March 6, 2014",3.93
0,12,Sugar,Maroon 5,"January 14, 2015",3.49
0,13,Sorry,Justin Bieber,"October 22, 2015",3.44
0,14,Dame Tu Cosita,El Chombo,"April 5, 2018",3.39
0,15,Roar,Katy Perry,"September 5, 2013",3.37
0,16,Counting Stars,OneRepublic,"May 31, 2013",3.32
0,17,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.27
0,18,Dark Horse,Katy Perry,"February 20, 2014",3.09
0,19,[44],Cocomelon – Nursery Rhymes,"May 24, 2018",3.08
0,20,Faded,Alan Walker,"December 3, 2015",3.08
0,21,Shake It Off,Taylor Swift,"August 18, 2014",3.07
0,22,Lean On,Major Lazer,"March 22, 2015",3.05
0,23,Girls Like You,Maroon 5,"May 31, 2018",3.05
0,24,Bailando,Enrique Iglesias,"April 11, 2014",3.05
0,25,Let Her Go,Passenger,"July 25, 2012",3.01
0,26,Mi Gente,J Balvin,"June 29, 2017",2.93
0,27,Perfect,Ed Sheeran,"November 9, 2017",2.87
0,28,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.85
0,29,Hello,Adele,"October 22, 2015",2.85
0,30,Axel F,Crazy Frog,"June 16, 2009",2.84

# BCCI

In [80]:
driver.get("https://www.bcci.tv/")

In [81]:
#go to international fixture page
element_international = driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]")
element_international.click()
time.sleep(10)
element_fixture = driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a")
element_fixture.click()

In [85]:
html = driver.page_source

In [86]:
soup = BS(html, 'html.parser')

In [132]:
bcci_df = pd.DataFrame({"Match Title":[],"Series":[],"Place":[],"Date":[],"Time":[]})

In [134]:
for row in soup.find("div",{"class":"js-list"}).findAll("a"):
    bcci_df = bcci_df.append(pd.DataFrame({
                                            "Match Title":row.findAll("div")[3].findAll("strong")[1].text,
                                            "Series":row.findAll("div")[3].findAll("div")[0].findAll("span")[1].text,
                                            "Place":row.findAll("div")[3].findAll("div")[1].findAll("span")[1].text,
                                            "Date":row.findAll("div")[3].findAll("div")[1].find("strong").text,
                                            "Time":row.findAll("div")[1].find("span",{"class":"fixture__time"}).text
                                            },index=[0]))

In [135]:
bcci_df

,Match Title,Series,Place,Date,Time
0,Final,ICC World Test Championship,"The Ageas Bowl, Southampton",Friday 18th June,15:00 IST
0,1st ODI,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Tuesday 13th July,14:30 IST
0,2nd ODI,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Friday 16th July,14:30 IST
0,3rd ODI,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Sunday 18th July,14:30 IST
0,1st T20I,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Wednesday 21st July,19:00 IST
0,2nd T20I,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Friday 23rd July,19:00 IST
0,3rd T20I,Sri Lanka v India 2021,"R Premadasa Stadium, Colombo",Sunday 25th July,19:00 IST
0,1st Test,England v India 2021,"Trent Bridge, Nottingham",Wednesday 4th August,15:30 IST
0,2nd Test,England v India 2021,"Lord's, London",Thursday 12th August,15:30 IST
0,3rd Test,England v India 2021,"Headingley, Leeds",Wednesday 25th August,15:30 IST
0,4th Test,England v India 2021,"The Oval, London",Thursday 2nd September,15:30 IST
0,5th Test,England v India 2021,"Old Trafford, Manchester",Friday 10th September,15:30 IST

# Guru99

In [264]:
driver.get("https://www.guru99.com/")

In [265]:
# Search for "exception handling selenium"
element_search = driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
element_search.send_keys('exception handling selenium')
time.sleep(10)
element_search_click = driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button")
element_search_click.click()
time.sleep(20)
search_result = driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div/div/div/div/div/div/div[2]/div/div[1]/div/div/div/div[1]/div[6]/div[2]/div/div/div[1]/div[1]/div[1]/div[1]/div/a")
search_result.click()
time.sleep(10)
driver.switch_to.window(driver.window_handles[-1])

In [186]:
html = driver.page_source

In [187]:
soup = BS(html, 'html.parser')

In [203]:
exception, description = [], []

In [204]:
for row in soup.find("table",{"class":"table table-striped"}).findAll("tr"):
    exception.append(row.findAll("td")[0].text)
    description.append(row.findAll("td")[1].text)

In [207]:
guru99_df = pd.DataFrame({"Exception":exception[1:],"Description":description[1:]})

In [208]:
guru99_df

,Exception,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# http://statisticstimes.com/

In [211]:
driver.get("http://statisticstimes.com/")

In [219]:
element_to_hover_over = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button")
hover = ActionChains(driver).move_to_element(element_to_hover_over)
hover.perform()
time.sleep(10)
element_to_click = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
element_to_click.click()

In [222]:
element_to_click = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

In [223]:
element_to_click.click()

In [224]:
html = driver.page_source

In [225]:
soup = BS(html, 'html.parser')

In [231]:
gdp_df = pd.DataFrame({"Rank":[],
                       "State":[],
                       "GSDP(18-19)":[],
                       "GSDP(17-18)":[],
                       "Share(2017)":[],
                       "GDP($ billion)":[]
                      })

In [253]:
for row in soup.find("table",{"class":"display dataTable"}).findAll("tr")[2:-1]:
    gdp_df = gdp_df.append(pd.DataFrame({
                                        "Rank":row.findAll("td")[0].text,
                                       "State":row.findAll("td")[1].text,
                                       "GSDP(18-19)":row.findAll("td")[3].text,
                                       "GSDP(17-18)":row.findAll("td")[7].text,
                                       "Share(2017)":row.findAll("td")[4].text,
                                       "GDP($ billion)":row.findAll("td")[5].text
                                        },index=[0]))

In [254]:
gdp_df

,Rank,State,GSDP(18-19),GSDP(17-18),Share(2017),GDP($ billion)
0,1,Maharashtra,"2,632,792","2,039,074",13.94%,399.921
0,2,Tamil Nadu,"1,630,208","1,215,307",8.63%,247.629
0,3,Uttar Pradesh,"1,584,764","1,123,982",8.39%,240.726
0,4,Gujarat,"1,502,899","1,186,379",7.96%,228.290
0,5,Karnataka,"1,493,127","1,091,077",7.91%,226.806
0,6,West Bengal,"1,089,898","739,525",5.77%,165.556
0,7,Rajasthan,"942,586","677,428",4.99%,143.179
0,8,Andhra Pradesh,"862,957","621,301",4.57%,131.083
0,9,Telangana,"861,031","612,828",4.56%,130.791
0,10,Madhya Pradesh,"809,592","522,009",4.29%,122.977
0,11,Kerala,"781,653","559,412",4.14%,118.733
0,12,Delhi,"774,870","590,569",4.10%,117.703
0,13,Haryana,"734,163","531,085",3.89%,111.519
0,14,Bihar,"530,363","375,651",2.81%,80.562
0,15,Punjab,"526,376","397,669",2.79%,79.957
0,16,Odisha,"487,805","376,877",2.58%,74.098
0,17,Assam,"315,881","234,048",1.67%,47.982
0,18,Chhattisgarh,"304,063","231,182",1.61%,46.187
0,19,Jharkhand,"297,204","224,986",1.57%,45.145
0,20,Uttarakhand,"245,895","193,273",1.30%,37.351
0,21,Jammu & Kashmir,"155,956","112,755",0.83%,23.690
0,22,Himachal Pradesh,"153,845","117,851",0.81%,23.369
0,23,Goa,"73,170","57,787",0.39%,11.115
0,24,Tripura,"49,845","36,963",0.26%,7.571
0,25,Chandigarh,"42,114","31,192",0.22%,6.397
0,26,Puducherry,"34,433","23,013",0.18%,5.230
0,27,Meghalaya,"33,481","24,682",0.18%,5.086
0,28,Sikkim,"28,723","18,722",0.15%,4.363
0,29,Manipur,"27,870","19,300",0.15%,4.233
0,30,Nagaland,"27,283","17,647",0.14%,4.144
0,31,Arunachal Pradesh,"24,603","16,676",0.13%,3.737
0,32,Mizoram,"22,287","16,478",0.12%,3.385
0,33,Andaman & Nicobar Islands,-,-,-,-